-- PostgreSQL schema bootstrap for mvc-v1.
BEGIN;

CREATE TABLE public.blog_posts (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title character varying(255) NOT NULL,
    excerpt character varying(1024) NOT NULL,
    content_html text NOT NULL,
    published_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX blog_posts_title_lower_unique
    ON public.blog_posts (lower(title));


COMMIT;
